### ISSUE TITLE
[MinedRanking]: 能整个实时更新吗？

### ISSUE THREAD

**Issue by Kogasa-touhou** [zhang-anzhi/MCDReforgedPlugins#10]
## Describe
A clear and concise description of your issue.

## Details
Some details for your issue.

**Comment by zhang-anzhi** [comment]
可以将更新间隔改为1s

**Comment by Kogasa-touhou** [comment]
可是控制台会被返回信息淹没啊！

**Comment by zhang-anzhi** [comment]
那你想怎么更新呢

**Comment by Kogasa-touhou** [comment]
如果返回信息可以不显示的话，那就太好了

**Comment by Kogasa-touhou** [comment]
![image](https://user-images.githubusercontent.com/67717065/117134634-63923700-add8-11eb-8578-d8093758b999.png)
在游戏中
我是op
我也会被刷屏

**Comment by zhang-anzhi** [comment]
请找到插件对应行把这个显示删掉即可

**Comment by Kogasa-touhou** [comment]
不止这个，设置为1，计分板会闪烁
设置为0就卡死了

**Comment by zhang-anzhi** [comment]
其他问题可以到 MCDReforged 讨论群交流
