### ISSUE TITLE
Suggestion: Why not use a faster third-party json library like ujson for implementation?

### ISSUE THREAD

**Issue by XiaoHuiHui233** [zhang-anzhi/MCDReforgedPlugins#12]
As we all know, the python standard json library has been criticized for its inefficient implementation. So since this project provides a convenient Json package, why not use some more efficient and easy-to-use third-party json library by the way. Like ujson, it has the same usage as the standard json library, except that it needs to be installed as a third-party library. This seems to reduce the experience a little bit, but compared to the efficiency improvement it brings, that is worthful.

There is no doubt about the efficiency improvement from these third-party json libraries. There are some evaluations about it:

[Benchmark of Python JSON libraries](https://artem.krylysov.com/blog/2015/09/29/benchmark-python-json-libraries/)
[Benchmark on home page of ujson library](https://pypi.org/project/ujson/)

And some of my light experience tells me that ujson is more than an order of magnitude faster than json. So why not use it?

**Comment by zhang-anzhi** [comment]
因为不想加个第三方库啊
