### ISSUE TITLE
suggestion info: More functions and bug

### ISSUE THREAD

**Issue by z0z0r4** [zhang-anzhi/MCDReforgedPlugins#16]
希望能够加入tps和mstp功能，和更多关于Minecraft 服务器本身的信息，例如server占用内存，在线人数，服务端版本信息和离线在线等

**Comment by zhang-anzhi** [comment]
MSPT原版无法获取，TPS原版获取方式不准确，建议使用mod
专用内存功能已经存在
在线人数不考虑增加因为tab即可显示
服务端版本信息和是否在线可以增加

**Comment by z0z0r4** [comment]
希望尽快出世awa

**Comment by zhang-anzhi** [comment]
在观望MCDR2.0

**Comment by zhang-anzhi** [comment]
再加一个：cpu温度

**Comment by zhang-anzhi** [comment]
新增：操作系统版本

**Comment by zhang-anzhi** [comment]
整理一下功能：

- [ ] 系统版本
- [ ] python版本
- [ ] cpu占用
- [ ] 内存占用
- [ ] 存档大小

**Comment by zhang-anzhi** [comment]
在线人数，服务端版本需要更多依赖，而这个插件更多是获取基础信息，所以不考虑

**Comment by zhang-anzhi** [comment]
server占用内存获取不稳定，考虑删除，仅提供总内存信息
