### ISSUE TITLE
[QQChat]: ChatBridge支持？

### ISSUE THREAD

**Issue by MAX-XiaoKui** [zhang-anzhi/MCDReforgedPlugins#18]
最近在用[ChatBridge](https://github.com/TISUnion/ChatBridge)
但是里面的QQ客户端[有bug不能用](https://github.com/TISUnion/ChatBridge/issues/14)
而且QQChat功能更丰富
我的服务器还是群组服（在代理端装MCDR没有什么用（而且MCDR不支持我用的Velocity代理端））
所以想要能支持ChatBridge
谢谢

**Comment by zhang-anzhi** [comment]
目前计划是将 QQChat 功能在我的 [ChatHub](https://github.com/CreatioStudio/ChatHub) 实现，届时可替换 ChatBridge 和 QQChat。没有将 QQChat 支持 ChatBridge 的计划，无法单向支持。

**Comment by MAX-XiaoKui** [comment]
既然没有Discord和Velocity的支持，那算了吧

**Comment by AnzhiZhang** [comment]
QQChat 已支持 MCDR2.0

**Comment by AnzhiZhang** [comment]
> 既然没有Discord和Velocity的支持，那算了吧

Velocity 的 [ChatHub](https://github.com/AnzhiZhang/ChatHub)
