### ISSUE TITLE
[bot]: /bot/readme.md 中的 config api 地址丢失

### ISSUE THREAD

**Issue by LIPiston** [zhang-anzhi/MCDReforgedPlugins#19]
## Describe
如标题

## Details
如标题

## Expected behavior
补全

## Screenshots
![image](https://user-images.githubusercontent.com/75552696/130323977-e26fcbee-125b-4bd3-8707-0eaeda8f0105.png)

## Additional context
无（（（

**Comment by zhang-anzhi** [comment]
链接错了，应该是 <https://github.com/hanbings/ConfigAPI>
