### ISSUE TITLE
QQChat 插件加载失败

### ISSUE THREAD

**Issue by RisingInIris2017** [zhang-anzhi/MCDReforgedPlugins#2]
## 系统环境
操作系统：Windows Server 2019 Datacenter
Python 版本：3.8.6-rc1（64bit）
## 服务端环境
MCDR 版本：0.9.6
Minecraft 服务端核心：Fabric
所有安装的 MCDR 插件：
```
!!MCDR plugin list
[MCDR] [12:31:52] [InfoReactor/INFO]: 7x 已加载插件
[MCDR] [12:31:52] [InfoReactor/INFO]: - CoolQAPI-MCDR.py
[MCDR] [12:31:52] [InfoReactor/INFO]: - daycount.py
[MCDR] [12:31:52] [InfoReactor/INFO]: - Here.py
[MCDR] [12:31:52] [InfoReactor/INFO]: - joinMOTD.py
[MCDR] [12:31:52] [InfoReactor/INFO]: - OnlinePlayerAPI.py
[MCDR] [12:31:52] [InfoReactor/INFO]: - QuickBackupM.py
[MCDR] [12:31:52] [InfoReactor/INFO]: - tps.py
[MCDR] [12:31:53] [InfoReactor/INFO]: 0x 已禁用插件
[MCDR] [12:31:53] [InfoReactor/INFO]: 1x 未加载插件
[MCDR] [12:31:53] [InfoReactor/INFO]: - QQChat.py
```
## 问题描述
已经安装了 `requirements.txt` 中包含的所有依赖模块。

安装完成后，服务器启动时，和使用
```!!MCDR plugin reloadall```
重载插件时，MCDR 抛出如下异常：
https://paste.ubuntu.com/p/RQ493Rz7wZ/

**Comment by zhang-anzhi** [comment]
能否发一下QQChat.py的内容，可能是插件不完整

**Comment by RisingInIris2017** [comment]
> 能否发一下QQChat.py的内容，可能是插件不完整

https://gist.github.com/RisingInIris2017/24c5e4ef0bf1b54f21b8517e9e66b929
这个是在服务端中经过配置的 QQChat.py 文件，理论上应该只改动了开头几行处的常量赋值。
行数和仓库中的 QQChat.py 一样多，都是 324 行。
您可以看一下是不是在我们修改过程当中改错了什么东西。

**Comment by zhang-anzhi** [comment]
是的，随便找一个在线文件比对工具就可以发现你们配置后的文件于原插件有大量不同
![image](https://user-images.githubusercontent.com/37402126/93274232-7249c080-f7ec-11ea-8149-1e1cd1724ff7.png)
![image](https://user-images.githubusercontent.com/37402126/93274251-81307300-f7ec-11ea-9cb9-10a78f251dc5.png)
大量的冒号被删除, 这在python脚本中是致命的

**Comment by zhang-anzhi** [comment]
建议重新下载插件并使用一个正常的编辑器进行配置，我也会考虑做一下配置文件

**Comment by RisingInIris2017** [comment]
> 建议重新下载插件并使用一个正常的编辑器进行配置，我也会考虑做一下配置文件

原来是这样！了解了，我再尝试一下，如果有新的问题我会回复在下面。
