### ISSUE TITLE
[JsonDataAPI]: MCDR 2.0!

### ISSUE THREAD

**Issue by eagle3236** [zhang-anzhi/MCDReforgedPlugins#21]
## Describe
MCDR 2.0 support

## Details
RT

## Expected behavior
RT

## Screenshots
-

## Additional context
-

**Comment by eagle3236** [comment]
虽然似乎没啥必要（

**Comment by zhang-anzhi** [comment]
2.0就不更了，如果为了插件兼容的话去Archive找1.0的就行了。2.0提供了config相关api，该插件不再维护了
