### ISSUE TITLE
[coloredChat]: 加载失败，没有 mcdreforged.info 这个模块。

### ISSUE THREAD

**Issue by HarrisonWellsjeb** [zhang-anzhi/MCDReforgedPlugins#25]
[coloredChat]: 加载失败，没有 `mcdreforged.info` 这个模块。(应该是个简单的问题，但是我不懂python所以没法解决)
![image](https://user-images.githubusercontent.com/61180107/151753125-9f9a10f0-9464-45e6-b6c9-b60b4e2d2a7b.png)

配置：
centOS8.5 x86_64
python：@3.8.latest
mcdr：@2.3.1
依赖包：
![image](https://user-images.githubusercontent.com/61180107/151753318-bf7a5350-9bd6-4eb4-8ed5-d4fdf55b5097.png)

mcdr安装方式：
下载： `pip install mcdreforged`
初始化： `python -m mcdreforged init`
ps：我记得旧版本有一个 `requirements.txt` 记录了四个依赖，该版本按照文档使用了`python init` 的方式，根目录中没有`requirements.txt`文件了，我自己也没有手动安装过之前依赖了，我想这个过程应该已经被init做过了吧。服务器可以启动，其他插件没有问题

**Comment by zhang-anzhi** [comment]
这可能是由于MCDR更新了，建议求助一下群里的开发者们，我有一段时间没有维护了。如果有人PR乐意接受

**Comment by HuajiMUR233** [comment]
刚刚尝试在 #26 中修复了一下这个问题

**Comment by zhang-anzhi** [comment]
> 刚刚尝试在 #26 中修复了一下这个问题

是否经过测试正常修复？

**Comment by HuajiMUR233** [comment]
测试了下，是正常的

**Comment by zhang-anzhi** [comment]
已在 #26 中修复
