### ISSUE TITLE
[Gamemode]: Adding structure support for MCDR 2.x

### ISSUE THREAD

**Issue by EasonSYC** [zhang-anzhi/MCDReforgedPlugins#27]
## Describe
In MCDR 2.x, it is impossible to depend on Python .py files other than the file itself same as MCDR 1.x. Therefore, it is strongly recommended to remove these two APIs.

## Details
For ConfigAPI, it is possible to use MCDR APIs to get coordinates, which is easy to be changed. For JSONDataAPI, it is possible to use similar methods to some other plugins (e.g. TimedQBM).

**Comment by EasonSYC** [comment]
Currently, my server is in MCDReforged 2.3.2 version with Python 3.9.10. I dropped the 3 python files (gamemode, JSONDataAPI, ConfigAPI) into the plugins folder and an error popped up in my console:

> Error invoking listener EventListener[plugin=gamemode@0.0.1,priority=1000,callback=<function on_load at 0x000001FFED922F70>]
> Traceback (most recent call last):
>   File "...\Python\Python39\site-packages\mcdreforged\plugin\plugin_manager.py", line 474, in trigger_listener
>     listener.execute(listener.plugin.server_interface, *args)
>   File "...\Python\Python39\site-packages\mcdreforged\plugin\plugin_event.py", line 79, in execute
>     return self.callback(*args, **kwargs)
>   File "plugins\Gamemode.py", line 50, in on_load
>     from ConfigAPI import Config
> ModuleNotFoundError: No module named 'ConfigAPI'

I believe this is due to the change of plugin loading logic, which leads to changes in external lib modules as said in the [document](https://mcdreforged.readthedocs.io/en/latest/migrate/1.x_to_2.x.html#modules).

**Comment by EasonSYC** [comment]
I commited the Pull Request and the plugin itself was tested in my server with success on all functions.

**Comment by zhang-anzhi** [comment]
The PR is #28

**Comment by Valistars** [comment]
我用的大概还是21年前后的版本，tp功能可以加入一个cd时长的配置吗

**Comment by AnzhiZhang** [comment]
> 我用的大概还是21年前后的版本，tp功能可以加入一个cd时长的配置吗

请论述该功能的必要性

**Comment by Valistars** [comment]
> > 我用的大概还是21年前后的版本，tp功能可以加入一个cd时长的配置吗
> 
> 请论述该功能的必要性

服务器面向的玩家普遍游戏深度较浅，游戏时长比较短，为节省赶路时间增强玩家之间的社交，曾经开启过tp功能一段时间，之后出现了部分玩家滥用的情况，用来帮其他人快速运输物品，规避死亡风险等操作，虽然能设置权限，但这样部分人也是服务器为数不多的核心玩家了，而且也不是抱有恶意利用的，于是经过讨论就关闭了，现在开启新的周目之后，有人提出了在其他服务器见到tp功能有一个30分钟的cd，如果我们能也设置一个差不多的cd时间会比较合适，大家都能接受。这是我们期望能够实现的，故来此询问。

**Comment by AnzhiZhang** [comment]
> > > 我用的大概还是21年前后的版本，tp功能可以加入一个cd时长的配置吗
> > 
> > 
> > 请论述该功能的必要性
> 
> 服务器面向的玩家普遍游戏深度较浅，游戏时长比较短，为节省赶路时间增强玩家之间的社交，曾经开启过tp功能一段时间，之后出现了部分玩家滥用的情况，用来帮其他人快速运输物品，规避死亡风险等操作，虽然能设置权限，但这样部分人也是服务器为数不多的核心玩家了，而且也不是抱有恶意利用的，于是经过讨论就关闭了，现在开启新的周目之后，有人提出了在其他服务器见到tp功能有一个30分钟的cd，如果我们能也设置一个差不多的cd时间会比较合适，大家都能接受。这是我们期望能够实现的，故来此询问。

tp功能并不能tp和传输物品，只能在旁观模式下tp，恢复生存模式还是在原来的位置
