### ISSUE TITLE
[AdvancedBan]增加对白名单的管理指令

### ISSUE THREAD

**Issue by InkEcau** [zhang-anzhi/MCDReforgedPlugins#7]
`!!whitelist add`
`!!whitelist remove`
`!!whitelist list`
这样我就可以放弃自己写的垃圾插件了（

**Comment by zhang-anzhi** [comment]
推荐使用[AdvancedWhitelist](https://github.com/Da-Dog/MCDR-Plugins/tree/master/MCDR-AdvancedWhitelist)呢
