### ISSUE TITLE
[Gamemode]: 能给gamemode插件加个权限控制吗

### ISSUE THREAD

**Issue by xiajibaluanshuo** [zhang-anzhi/MCDReforgedPlugins#9]
###

## Details
Some details for your issue.

**Comment by zhang-anzhi** [comment]
同样的功能可以用FreeCamera实现，没必要加权限控制

**Comment by xiajibaluanshuo** [comment]
> 同样的功能可以用FreeCamera实现，没必要加权限控制

我想用做管理工具，可以观察者查熊的同时可以避免管理员滥用tp什么的权限

**Comment by zhang-anzhi** [comment]
已更新
